services:
  db_postgres:
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - db_postgres
    networks:
      - app-network
    volumes:
      - ./backend:/app-backend  # Para desenvolvimento (remover em produção)
      - /app-backend/node_modules  # Preserva node_modules do contêiner
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app-frontend  # Para desenvolvimento (remover em produção)
      - /app-frontend/node_modules  # Preserva node_modules do contêiner
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge